export const LOGIN_SUCESS = 'LOGIN_SUCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const REGISTER_SUCESS = 'REGISTER_SUCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const AUTHENTICATION_SUCESS = 'AUTHENTICATION_SUCESS';
export const AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED';
export const LOGOUT_USER = 'LOGOUT_USER';